"""Add customer to sales

Revision ID: 154e8163c660
Revises: f01bec497afa
Create Date: 2026-08-10 12:30:50.832538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154e8163c660'
down_revision = 'f01bec497afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
