"""Make user email unique

Revision ID: 9f3a7c21b5e4
Revises: 154e8163c660
Create Date: 2026-08-10 23:22:45.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3a7c21b5e4'
down_revision = '154e8163c660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(
            batch_op.f('ix_users_email'),
            ['email'],
            unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(
            batch_op.f('ix_users_email'),
            ['email'],
            unique=False
        )

    # ### end Alembic commands ###